package com.example.fitnessapp.util

import com.example.fitnessapp.domain.IntModel
import com.example.fitnessapp.domain.StringModel

object Constants {
    val list = listOf(
        IntModel(0),
        IntModel(0),
        IntModel(1),
        IntModel(2),
        IntModel(3),
        IntModel(4),
        IntModel(5),
        IntModel(6),
        IntModel(7),
        IntModel(8),
        IntModel(9),
        IntModel(10),
        IntModel(11),
        IntModel(12),
        IntModel(13),
        IntModel(14),
        IntModel(15),
        IntModel(16),
        IntModel(17),
        IntModel(18),
        IntModel(19),
        IntModel(20),
        IntModel(21),
        IntModel(22),
        IntModel(23),
        IntModel(24),
        IntModel(25),
        IntModel(26),
        IntModel(27),
        IntModel(28),
        IntModel(29),
        IntModel(30),
        IntModel(31),
        IntModel(32),
        IntModel(33),
        IntModel(34),
        IntModel(35),
        IntModel(36),
        IntModel(37),
        IntModel(38),
        IntModel(39),
        IntModel(40),
        IntModel(41),
        IntModel(42),
        IntModel(43),
        IntModel(44),
        IntModel(45),
        IntModel(46),
        IntModel(47),
        IntModel(48),
        IntModel(49),
        IntModel(50),
        IntModel(51),
        IntModel(52),
        IntModel(53),
        IntModel(54),
        IntModel(55),
        IntModel(56),
        IntModel(57),
        IntModel(58),
        IntModel(59),
        IntModel(60),
        IntModel(61),
        IntModel(62),
        IntModel(63),
        IntModel(64),
        IntModel(65),
        IntModel(66),
        IntModel(67),
        IntModel(68),
        IntModel(69),
        IntModel(70),
        IntModel(71),
        IntModel(72),
        IntModel(73),
        IntModel(74),
        IntModel(75),
        IntModel(76),
        IntModel(77),
        IntModel(78),
        IntModel(79),
        IntModel(80),
        IntModel(81),
        IntModel(82),
        IntModel(83),
        IntModel(84),
        IntModel(85),
        IntModel(86),
        IntModel(87),
        IntModel(88),
        IntModel(89),
        IntModel(90),
        IntModel(91),
        IntModel(92),
        IntModel(93),
        IntModel(94),
        IntModel(95),
        IntModel(96),
        IntModel(97),
        IntModel(98),
        IntModel(99),
        IntModel(100),
        IntModel(0),
        IntModel(0),
    )
    val listGoal = listOf(
        StringModel(""),
        StringModel("Gain Weight"),
        StringModel("Lose weight"),
        StringModel("Get fitter"),
        StringModel("Gain more flexible"),
        StringModel("Learn the basic"),
        StringModel(""),
    )
    val listActivityLevel = listOf(
        StringModel(""),
        StringModel("Rookie"),
        StringModel("Beginner"),
        StringModel("Intermediate"),
        StringModel("Advance"),
        StringModel("True Beast"),
        StringModel(""),
    )
}